services:
  ecommerce-rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    hostname: ecommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ecommerce-redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ecommerce-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: ecommerce-azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    volumes:
      - azurite_data:/data

volumes:
  rabbitmq_data:
  redis_data:
  azurite_data: