<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Services\Cart\ECommerce.Cart.Domain\ECommerce.Cart.Domain.csproj" />
    <ProjectReference Include="..\..\Services\Catalog\ECommerce.Catalog.Domain\ECommerce.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\Services\Identity\ECommerce.Identity.Domain\ECommerce.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Services\Inventory\ECommerce.Inventory.Domain\ECommerce.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\Services\Ordering\ECommerce.Ordering.Domain\ECommerce.Ordering.Domain.csproj" />
    <ProjectReference Include="..\..\Services\Payment\ECommerce.Payment.Domain\ECommerce.Payment.Domain.csproj" />
  </ItemGroup>
</Project>