<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="SqlServer\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Core.SharedLibs\ECommerce.Core.SharedLibs.csproj" />
    <ProjectReference Include="..\ECommerce.Domain.Core\ECommerce.Domain.Core.csproj" />
  </ItemGroup>
</Project>