<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.9.2" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Data\ECommerce.Catalog.Data.csproj" />
    <ProjectReference Include="..\ECommerce.Core.SharedLibs\ECommerce.Core.SharedLibs.csproj" />
    <ProjectReference Include="..\ECommerce.Identity.Service\ECommerce.Identity.Service.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.BackgroundJobs\ECommerce.Infrastructure.BackgroundJobs.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Kafka\ECommerce.Infrastructure.Kafka.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Observability\ECommerce.Infrastructure.Observability.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Payment\ECommerce.Infrastructure.Payment.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Persistence\ECommerce.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.RabbitMq\ECommerce.Infrastructure.RabbitMq.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Redis\ECommerce.Infrastructure.Redis.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Security.Core\ECommerce.Infrastructure.Security.Core.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Security\ECommerce.Infrastructure.Security.csproj" />
    <ProjectReference Include="..\ECommerce.Inventory.Service\ECommerce.Inventory.Service.csproj" />
    <ProjectReference Include="..\ECommerce.Ordering.Service\ECommerce.Ordering.Service.csproj" />
    <ProjectReference Include="..\ECommerce.Payment.Service\ECommerce.Payment.Service.csproj" />
    <ProjectReference Include="..\Service\ECommerce.Catalog.Service.csproj" />
    <ProjectReference Include="..\ECommerce.Domain.Core\ECommerce.Domain.Core.csproj" />
  </ItemGroup>
</Project>