<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.2" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Core.SharedLibs\ECommerce.Core.SharedLibs.csproj" />
    <ProjectReference Include="..\ECommerce.Domain.Core\ECommerce.Domain.Core.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Persistence\ECommerce.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure.Security.Core\ECommerce.Infrastructure.Security.Core.csproj" />
  </ItemGroup>
</Project>
